---
# Source: api_chart/templates/api.yaml
#service manifest for nodejstest1
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: dev
  labels:
    app: go-app
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
    - port: 80
---
# Source: api_chart/templates/api.yaml
#deployment manifest for nodejstest1
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app
  labels:
    app: go-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Type
      #           operator: NotIn
      #           values:
      #           - stateful
    containers:
    - name: go-app
    image: "012569964433.dkr.ecr.eu-west-1.amazonaws.com/go-app:690a043a5"
    pullPolicy: IfNotPresent
    # env:
    #   - name: student
    #     valueFrom:
    #       secretKeyRef:
    #         name: student-secret
    #         key: student
    ports:
    - containerPort: 3000
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause:
          duration: "60s" # 1 hour
      - setWeight: 50
      - pause: {} # pause indefinitely
