---
# Source: api_chart/templates/api.yaml
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: dev
  labels:
    app: go-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: go-app
---
# Source: api_chart/templates/api.yaml
#deployment manifest for nodejstest1
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app
  labels:
    app: go-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Type
      #           operator: NotIn
      #           values:
      #           - stateful
      pullPolicy: IfNotPresent
      containers:
        - name: go-app
          image: "012569964433.dkr.ecr.eu-west-1.amazonaws.com/go-app:9bb0a1e23"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP 
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
  revisionHistoryLimit: 3
  strategy:
    canary: # A new field that used to provide configurable options for a Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 50
      - pause: {}
